# Generated by Django 5.2.4 on 2025-08-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('fallower_count', models.IntegerField(default=0)),
                ('alert_threshold', models.IntegerField(default=1000)),
                ('telegram_chat_id', models.CharField(max_length=100)),
            ],
        ),
    ]
